### PR TITLE
code format

### PR DESCRIPTION
**Pull request by islishude**
gofmt -w .

### CODE REVIEW

**Comment by islishude** [comment]
Anyone reviews?

**Comment by renlulu** [comment]
> Anyone reviews?
Hey, thanks, but can you change this pr to be merged to branch `dev` Thanks!

**Comment by islishude** [comment]
@renlulu done

**Comment by renlulu** [comment]
> @renlulu done

Thanks a lot!

**Comment by islishude** [comment]
ping. @bb111189 @renlulu 

Could anyone merge it?

**Comment by renlulu** [comment]
> ping. @bb111189 @renlulu
> 
> Could anyone merge it?

Merged, thanks!

**Pull request merged**
